import os

DEBUG = True
SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') + "?sslmode=require"
SECRET_KEY = os.environ.get('SECRET_KEY') 
SECURITY_REGISTERABLE = os.environ.get('SECURITY_REGISTERABLE') 
SECURITY_PASSWORD_HASH = os.environ.get('SECURITY_PASSWORD_HASH')  
SECURITY_PASSWORD_SALT = os.environ.get('SECURITY_PASSWORD_SALT') 