"""added Curriculum Table with Curriculum Namr etc

Revision ID: 602d7ba10882
Revises: a1f78aa900b2
Create Date: 2019-05-23 20:15:22.496381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602d7ba10882'
down_revision = 'a1f78aa900b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_name', sa.String(length=80), nullable=True),
    sa.Column('curriculum_year_level', sa.Integer(), nullable=True),
    sa.Column('curriculum_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('curriculum_item', sa.Column('curriculum_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'curriculum_item', 'curriculum', ['curriculum_id'], ['id'])
    op.drop_column('curriculum_item', 'year_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_item', sa.Column('year_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'curriculum_item', type_='foreignkey')
    op.drop_column('curriculum_item', 'curriculum_id')
    op.drop_table('curriculum')
    # ### end Alembic commands ###
