"""Removed relationship between subjects and curriculum items - can't figure what the fuck is with dropdown

Revision ID: 61fc851d5963
Revises: 602d7ba10882
Create Date: 2019-05-26 13:22:55.757759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fc851d5963'
down_revision = '602d7ba10882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_item', sa.Column('subject', sa.String(length=80), nullable=True))
    op.drop_constraint('curriculum_item_subject_id_fkey', 'curriculum_item', type_='foreignkey')
    op.drop_column('curriculum_item', 'subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_item', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('curriculum_item_subject_id_fkey', 'curriculum_item', 'subjects', ['subject_id'], ['id'])
    op.drop_column('curriculum_item', 'subject')
    # ### end Alembic commands ###
