"""questionaire changes with questionarie type added

Revision ID: 6ae90fceb335
Revises: cd4de571c435
Create Date: 2018-10-08 09:26:55.466508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae90fceb335'
down_revision = 'cd4de571c435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionaire', sa.Column('questionaire_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionaire', 'questionaire_type')
    # ### end Alembic commands ###
