"""second migrate

Revision ID: b77c734e6a29
Revises: f71e7e2a0913
Create Date: 2018-08-25 22:05:11.205348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77c734e6a29'
down_revision = 'f71e7e2a0913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class_list', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('class_list_participant_id_fkey', 'class_list', type_='foreignkey')
    op.create_foreign_key(None, 'class_list', 'person', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_list', type_='foreignkey')
    op.create_foreign_key('class_list_participant_id_fkey', 'class_list', 'child', ['participant_id'], ['id'])
    op.alter_column('class_list', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
