"""questionaire changes

Revision ID: cd4de571c435
Revises: e1331e9c3189
Create Date: 2018-10-06 18:53:31.496378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4de571c435'
down_revision = 'e1331e9c3189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionaire_name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionaire_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionaire_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=120), nullable=True),
    sa.Column('response', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionaire_id'], ['questionaire.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_questionaire_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questionaire_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_questionaire_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questionaire_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('class_program', sa.Column('program_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_program', 'program_description')
    op.drop_table('customer_questionaire_questions')
    op.drop_table('child_questionaire_questions')
    op.drop_table('questionaire_questions')
    op.drop_table('questionaire')
    # ### end Alembic commands ###
