"""first migrate

Revision ID: f71e7e2a0913
Revises: 
Create Date: 2018-08-25 21:53:57.945452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71e7e2a0913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_value', sa.Float(), nullable=True),
    sa.Column('cost_name', sa.String(length=80), nullable=True),
    sa.Column('cost_incurred_date', sa.DateTime(), nullable=False),
    sa.Column('includes_gst', sa.Boolean(), nullable=True),
    sa.Column('cost_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=80), nullable=True),
    sa.Column('day_of_class', sa.String(length=80), nullable=True),
    sa.Column('lesson_time', sa.DateTime(), nullable=True),
    sa.Column('lesson_duration', sa.Integer(), nullable=True),
    sa.Column('lesson_cost', sa.Float(), nullable=True),
    sa.Column('lesson_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('street_address', sa.String(length=150), nullable=True),
    sa.Column('suburb', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternative_contact', sa.String(length=100), nullable=True),
    sa.Column('alternative_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=True),
    sa.Column('payment_name', sa.String(length=80), nullable=True),
    sa.Column('payment_type', sa.String(length=80), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('includes_gst', sa.Boolean(), nullable=True),
    sa.Column('cost_description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_list')
    op.drop_table('payments')
    op.drop_table('child')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('person')
    op.drop_table('lesson')
    op.drop_table('business_costs')
    # ### end Alembic commands ###
